### ISSUE TITLE
No JSON object returned from GET

### ISSUE THREAD

**Issue by jtrotsky** [poynt/python-sample#5]
When running the app in the default live environment I get a crash due to a 304 returned after GET https://services.poynt.net/businesses/2af9201b-316d-492f-a1b1-8278e7793254/orders/390002d5-626f-4002-a7a5-3f67354e247a

If I get that URL via Postman from my browser (using the same jwt), then the response I get is 200 and a JSON payload.

It seems to be that the custom header being added in the app is causing the 304 response:
https://github.com/poynt/python-sample/blob/master/src/PoyntAPI.py#L326

If you remove this header then the response completes with 200 and returns the JSON payload correctly.

Is there any reason to set the `Is-Modified-Since` header?

```
Fetching an Order:
    GET https://services.poynt.net/businesses/2af9201b-316d-492f-a1b1-8278e7793254/orders/390002d5-626f-4002-a7a5-3f67354e247a
    HTTP RESPONSE CODE:304
    RESPONSE TIME: 916.22 msecs
Traceback (most recent call last):
  File "./src/PoyntAPI.py", line 708, in <module>
    main(sys.argv[1:])
  File "./src/PoyntAPI.py", line 690, in main
    poyntAPI.createOrder(BUSINESS_ID, STORE_ID)
  File "./src/PoyntAPI.py", line 319, in createOrder
    self.getOrder(businessId, jsonObj['id'])
  File "./src/PoyntAPI.py", line 328, in getOrder
    code, jsonObj = self._sendGetRequest(poyntOrderUrl, {}, headers)
  File "./src/PoyntAPI.py", line 619, in _sendGetRequest
    return r.status_code, r.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ppalavilli** [comment]
304 is not an error condition - it only means that the given resource has not modified since the time indicated in the "If-Modified-Since" header.  Let me update the code accordingly.

**Comment by ppalavilli** [comment]
Done: https://github.com/poynt/python-sample/commit/14bcd51c172056a8f19b523c368a37c2ec0a28e1

**Comment by jtrotsky** [comment]
Man you're quick @ppalavilli :)
